services:
  hetzner_ddns:
    container_name: hetzner_ddns
    build: .
    environment:
      MY_DOMAIN: ${MY_DOMAIN}
      HETZNER_API_TOKEN: "${HETZNER_API_TOKEN}"
    env_file:
      - .secrets.env
    volumes:
      - ./state.json:/app/state.json
    restart: unless-stopped
