services:
  emby:
    image: emby/embyserver:4.9.4.1
    container_name: embyserver
    # network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=1000,44,105
    volumes:
      - /mnt/media0/emby/config:/config
      - /mnt/media0/emby/media:/media
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
